### ISSUE TITLE
Atomicwallet does not run on Ubuntu 14.04 

### ISSUE THREAD

**Issue by probonopd** [Atomicwallet/atomicwallet.github.io#1]
The AppImage does not run on Ubuntu 14.04 because some of its ingredients were apparently compiled on a "too new" system.

```
Xlib:  extension "RANDR" missing on display ":99".
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.qFhHn1)
```

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems and https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6.

Reference:
* https://github.com/AppImage/appimage.github.io/pull/689

**Comment by dractw** [comment]
> I couldn't find the installation files for Atomic Wallet here on GitHub (I know the executable is hosted on the site), are those open-source too or closed-source/mixed-source?

Hi, atomicwallet currenlty is a closed-source project.
